# Generated by Django 6.0.4 on 2026-04-12 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='logs/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzed', 'Analyzed'), ('verified', 'Verified')], default='uploaded', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('total_lines', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('debug_count', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('critical_lines', models.TextField(default='[]')),
                ('anomaly_lines', models.TextField(default='[]')),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.logfile')),
            ],
        ),
    ]
